name: "Caller Workflow"

on:
  workflow_dispatch:

jobs:
  Build-Infra:
    # Run the Infra Workflow
    uses: yossisp1972/movie-bot-infra/.github/workflows/infra.yaml@master
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}