name: "Infra Workflow"
on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform init
        run: terraform init
        working-directory: ./tf
        
      - name: Terraform plan
        run: terraform plan -out=tfplan
        working-directory: ./tf

      - name: Terraform apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./tf

      # - name: Terraform Output
      #   id: tf-output
      #   run: |
      #     terraform output -raw eks_cluster_name > cluster_name.txt

      - name: Export Terraform Outputs to GitHub Environment
        id: export_outputs
        run: |
          TERRAFORM_OUTPUTS=$(terraform output -json)
          terraform output -json
          echo "cluster_name=$(echo $TERRAFORM_OUTPUTS | jq -r '.cluster_name.value')" >> $GITHUB_OUTPUT
          # echo "my_ip_address=$(echo $TERRAFORM_OUTPUTS | jq -r '.my_ip_address.value')" >> $GITHUB_OUTPUT
          echo "argocd_server_hostname=$(echo $TERRAFORM_OUTPUTS | jq -r '.argocd_server_hostname.value')" >> $GITHUB_OUTPUT
        working-directory: ./tf

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name ${{steps.export_outputs.outputs.cluster_name}}

      - name: Get argocd details
        run: |
          ARGOCD_PASSWORD=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)
          echo "argocd password=$ARGOCD_PASSWORD"
          echo "ArgoCD is available at: https://${{steps.export_outputs.outputs.argocd_server_hostname}}"
